import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { database, ai, redis, github, email, branding, features, nexusSecret } = body;

    if (!database || !nexusSecret) {
      return NextResponse.json(
        { error: 'Database and secret key are required' },
        { status: 400 }
      );
    }

    // Build .env content
    let envContent = `# Nexus Environment Configuration
# Generated by installation wizard
# Generated at: ${new Date().toISOString()}
# IMPORTANT: This file should have permissions 600 (chmod 600 .env)

# ================================================
# DATABASE (PostgreSQL)
# ================================================
DATABASE_HOST=${database.host}
DATABASE_PORT=${database.port}
DATABASE_NAME=${database.name}
DATABASE_USER=${database.user}
DATABASE_PASSWORD=${database.password}

# ================================================
# NEXUS AUTH
# ================================================
NEXUS_SECRET_KEY=${nexusSecret}

# ================================================
# AI PROVIDERS (Optional)
# ================================================
`;
    
    if (ai?.openaiKey) {
      envContent += `OPENAI_API_KEY=${ai.openaiKey}\n`;
    }
    if (ai?.anthropicKey) {
      envContent += `ANTHROPIC_API_KEY=${ai.anthropicKey}\n`;
    }
    if (ai?.minimaxKey) {
      envContent += `MINIMAX_API_KEY=${ai.minimaxKey}\n`;
    }

    envContent += `
# ================================================
# REDIS CACHE (Optional)
# ================================================
REDIS_HOST=${redis?.host || 'localhost'}
REDIS_PORT=${redis?.port || '6379'}
REDIS_PASSWORD=${redis?.password || ''}
REDIS_KEY_PREFIX=${redis?.keyPrefix || 'nexus:'}

# ================================================
# GITHUB OAUTH (Optional)
# ================================================
GITHUB_CLIENT_ID=${github?.clientId || ''}
GITHUB_CLIENT_SECRET=${github?.clientSecret || ''}
GITHUB_REDIRECT_URI=${github?.redirectUri || 'http://localhost:3000/api/github/callback'}

# ================================================
# EMAIL PROVIDER (Optional)
# ================================================
EMAIL_HOST=${email?.host || ''}
EMAIL_PORT=${email?.port || '587'}
EMAIL_USER=${email?.user || ''}
EMAIL_PASSWORD=${email?.password || ''}
EMAIL_FROM_NAME=${email?.fromName || 'Nexus AI'}
EMAIL_FROM_EMAIL=${email?.fromEmail || 'noreply@nexus.local'}
EMAIL_PROVIDER=${email?.provider || 'smtp'}

# ================================================
# SITE BRANDING
# ================================================
SITE_NAME=${branding?.siteName || 'Nexus AI'}
SITE_DESCRIPTION=${branding?.siteDescription || 'AI-Powered Development Platform'}
SITE_LOGO=${branding?.siteLogo || '/favicon.ico'}
PRIMARY_COLOR=${branding?.primaryColor || '#8b5cf6'}
SECONDARY_COLOR=${branding?.secondaryColor || '#3b82f6'}
ACCENT_COLOR=${branding?.accentColor || '#06b6d4'}
FOOTER_TEXT=${branding?.footerText || 'Powered by Nexus AI'}

# ================================================
# FEATURES
# ================================================
ALLOW_REGISTRATION=${features?.allowRegistration ? 'true' : 'false'}
ENABLE_BILLING=${features?.enableBilling ? 'true' : 'false'}
ENABLE_GITHUB_INTEGRATION=${features?.enableGithubIntegration ? 'true' : 'false'}
`;

    // Get the path to write the .env file
    // We write to process.cwd() which is /app in the container
    // The docker-compose env_file will load from .env in the site root
    const envPath = path.join(process.cwd(), '.env');
    
    // Write the file
    fs.writeFileSync(envPath, envContent, 'utf8');
    
    // Also set file permissions to 600 (owner read/write only)
    try {
      fs.chmodSync(envPath, 0o600);
    } catch (e) {
      console.warn('Could not set file permissions:', e);
    }

    return NextResponse.json({ 
      success: true,
      message: 'Configuration saved to .env file. Run "docker compose down && docker compose up -d" to apply.',
      envPath
    });
  } catch (error: any) {
    console.error('Error saving config:', error);
    return NextResponse.json(
      { error: 'Failed to save configuration: ' + error.message },
      { status: 500 }
    );
  }
}
