import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { database, ai, redis, github, email, branding, features, nexusSecret } = body;

    if (!database || !nexusSecret) {
      return NextResponse.json(
        { error: 'Database and secret key are required' },
        { status: 400 }
      );
    }

    // Generate environment variables instead of writing to file
    // For production, set these in CloudPanel or docker-compose environment section
    const envConfig = `# Nexus Configuration
# Generated by installation wizard
# Generated at: ${new Date().toISOString()}
# Copy these to your CloudPanel environment variables or .env file

# ================================================
# DATABASE (PostgreSQL)
# ================================================
DATABASE_HOST=${database.host}
DATABASE_PORT=${database.port}
DATABASE_NAME=${database.name}
DATABASE_USER=${database.user}
DATABASE_PASSWORD=${database.password}

# ================================================
# NEXUS AUTH
# ================================================
NEXUS_SECRET_KEY=${nexusSecret}

# ================================================
# AI PROVIDERS (Optional)
# ================================================
${ai?.openaiKey ? `OPENAI_API_KEY=${ai.openaiKey}` : ''}
${ai?.anthropicKey ? `ANTHROPIC_API_KEY=${ai.anthropicKey}` : ''}
${ai?.minimaxKey ? `MINIMAX_API_KEY=${ai.minimaxKey}` : ''}

# ================================================
# REDIS CACHE (Optional)
# ================================================
REDIS_HOST=${redis?.host || 'localhost'}
REDIS_PORT=${redis?.port || '6379'}
REDIS_PASSWORD=${redis?.password || ''}
REDIS_KEY_PREFIX=${redis?.keyPrefix || 'nexus:'}

# ================================================
# GITHUB OAUTH (Optional)
# ================================================
GITHUB_CLIENT_ID=${github?.clientId || ''}
GITHUB_CLIENT_SECRET=${github?.clientSecret || ''}
GITHUB_REDIRECT_URI=${github?.redirectUri || 'http://localhost:3000/api/github/callback'}

# ================================================
# EMAIL PROVIDER (Optional)
# ================================================
EMAIL_HOST=${email?.host || ''}
EMAIL_PORT=${email?.port || '587'}
EMAIL_USER=${email?.user || ''}
EMAIL_PASSWORD=${email?.password || ''}
EMAIL_FROM_NAME=${email?.fromName || 'Nexus AI'}
EMAIL_FROM_EMAIL=${email?.fromEmail || 'noreply@nexus.local'}
EMAIL_PROVIDER=${email?.provider || 'smtp'}

# ================================================
# SITE BRANDING
# ================================================
SITE_NAME=${branding?.siteName || 'Nexus AI'}
SITE_DESCRIPTION=${branding?.siteDescription || 'AI-Powered Development Platform'}
SITE_LOGO=${branding?.siteLogo || '/favicon.ico'}
PRIMARY_COLOR=${branding?.primaryColor || '#8b5cf6'}
SECONDARY_COLOR=${branding?.secondaryColor || '#3b82f6'}
ACCENT_COLOR=${branding?.accentColor || '#06b6d4'}
FOOTER_TEXT=${branding?.footerText || 'Powered by Nexus AI'}

# ================================================
# FEATURES
# ================================================
ALLOW_REGISTRATION=${features?.allowRegistration ? 'true' : 'false'}
ENABLE_BILLING=${features?.enableBilling ? 'true' : 'false'}
ENABLE_GITHUB_INTEGRATION=${features?.enableGithubIntegration ? 'true' : 'false'}
`;

    return NextResponse.json({ 
      success: true, 
      envConfig,
      message: 'Configuration generated. Set these environment variables in CloudPanel and restart the container.'
    });
  } catch (error: any) {
    console.error('Error generating config:', error);
    return NextResponse.json(
      { error: 'Failed to generate configuration: ' + error.message },
      { status: 500 }
    );
  }
}
