import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { supabaseUrl, supabaseAnonKey, supabaseServiceKey } = body;

    if (!supabaseUrl || !supabaseAnonKey) {
      return NextResponse.json(
        { error: 'URL and anon key are required' },
        { status: 400 }
      );
    }

    // Create config content
    const configContent = `# Nexus Configuration
# Generated by installation wizard

NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseAnonKey}
SUPABASE_SERVICE_KEY=${supabaseServiceKey || ''}
`;

    // Write to config file in the app directory
    const configPath = path.join(process.cwd(), '.env.nexus');
    fs.writeFileSync(configPath, configContent, 'utf8');

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error saving config:', error);
    return NextResponse.json(
      { error: 'Failed to save configuration' },
      { status: 500 }
    );
  }
}

export async function GET() {
  // Check if config exists
  const configPath = path.join(process.cwd(), '.env.nexus');
  const configExists = fs.existsSync(configPath);
  
  return NextResponse.json({
    configured: configExists
  });
}
